### ISSUE TITLE
for intf in /sys/devices/virtual/net/docker0/bri f/*; do echo 1 > $intf/hairpin_mode; done

### ISSUE THREAD

**Issue by zetterma** [opsnull/follow-me-install-kubernetes-cluster#252]
你好，设置系统参数时，运行这个命令提示“未找到文件或文件夹”，这个是要装什么东西么？

**Comment by watermelonbig** [comment]
这个是要配置docker网卡的通信模式为hairpin mode。实际上在这个步骤时，还没安装docker引擎，也没启动任何容器。
因此这些要配置的网卡还不存在。



watermelonbig@163.com
 
From: zetterma
Date: 2018-07-02 17:29
To: opsnull/follow-me-install-kubernetes-cluster
CC: Subscribed
Subject: [opsnull/follow-me-install-kubernetes-cluster] for intf in /sys/devices/virtual/net/docker0/bri f/*; do echo 1 > $intf/hairpin_mode; done (#252)
你好，设置系统参数时，运行这个命令提示“未找到文件或文件夹”，这个是要装什么东西么？

**Comment by opsnull** [comment]
多谢反馈，已更正！

**Comment by lilongabc** [comment]
请问如何处理 解决此问题，我也是这个爆粗，而且我的docker 0网卡也没了。报错如下：
[root@kube-node1 ~]# for intf in /sys/devices/virtual/net/docker0/brif/*; do echo 1 > $intf/hairpin_mode; done
-bash: /sys/devices/virtual/net/docker0/brif/*/hairpin_mode: No such file or directory

**Comment by lilongabc** [comment]
[root@kube-node1 ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-07-26 19:21:35 CST; 3s ago
     Docs: http://docs.docker.io
  Process: 30337 ExecStart=/opt/k8s/bin/dockerd --log-level=error $DOCKER_NETWORK_OPTIONS (code=exited, status=203/EXEC)
 Main PID: 30337 (code=exited, status=203/EXEC)

**Comment by opsnull** [comment]
@lilongabc 看最新的文档，在启动 docker 后再自行这个命令，就 OK 了。

**Comment by duoyichen** [comment]
我是照着最新文档，启动 docker 后再执行这个命令，还是报这个错，不知道什么原因？
我以前 yum install docker-ce
后来又 yum remove docker-ce 
然后下载 docker-18.03.1-ce.tgz 按照文档操作的，是因为这个原因吗？

**Comment by duoyichen** [comment]
@opsnull 
我是照着最新文档，启动 docker 后再执行这个命令，还是报这个错，不知道什么原因？
我以前 yum install docker-ce
后来又 yum remove docker-ce
然后下载 docker-18.03.1-ce.tgz 按照文档操作的，是因为这个原因吗？

或者，我可以跳过这一步吗？

**Comment by Tianny** [comment]
> @opsnull
> 我是照着最新文档，启动 docker 后再执行这个命令，还是报这个错，不知道什么原因？
> 我以前 yum install docker-ce
> 后来又 yum remove docker-ce
> 然后下载 docker-18.03.1-ce.tgz 按照文档操作的，是因为这个原因吗？
> 
> 或者，我可以跳过这一步吗？

在验证集群功能的时候，就是跑 nginx-ds 为 running 后，这个brif 下就有对应的文件了。就可以进行操作了
